# This file is used to package this project as a pip package.


[build-system]
requires = ["py-build-cmake"]
build-backend = "py_build_cmake.build"


[project]
name = "khiops-driver-azure"
readme = "README.md"
requires-python = ">=3.9"
license = "BSD-3-Clause-Clear"
license-files = ["LICENSE"]
maintainers = [{name = "Khiops Team", email = "khiops.team@orange.com"}]
dynamic = ["version", "description"]


[tool.py-build-cmake.module]
name = "metadata"  # The metadata.py module will be run to set the package version and description

[tool.py-build-cmake.sdist]
include = ["*"]
exclude = [
    ".*",
    "__pycache__",
    "dist",
    "wheelhouse",
    "scripts",
    "test/LearningTest",
    "test/LearningTestTool",
    "vcpkg/buildtrees",
    "vcpkg/downloads",
    "vcpkg/packages"
]

[tool.py-build-cmake.cmake]
minimum_version = "3.21"
find_python = false   # No need for Python
find_python3 = false   # No need for Python
options = {CMAKE_TOOLCHAIN_FILE = "vcpkg/scripts/buildsystems/vcpkg.cmake"}
build_type = "Release"
config = ["Release"]

[tool.py-build-cmake.linux.cmake]
generator = "Ninja"

[tool.py-build-cmake.mac.cmake]
generator = "Ninja"

[tool.py-build-cmake.windows.cmake]
generator = "Visual Studio 17 2022"  # We can't use Ninja on windows because we need both 32- and 64-bits wheels; Ninja only builds host-platform binaries


[tool.py-build-cmake.wheel]
python_tag = "py3"  # We do not depend on Python
python_abi = "none"  # We do not depend on Python


[tool.cibuildwheel]
build = "cp39-*"
skip = "*musllinux*"  # Khiops itself does not compile under musl linuxes, so there is no need for musl linux Khiops drivers

[tool.cibuildwheel.linux]
before-all = [
    "DEB_NEEDS='zip perl ninja-build'",
    "FED_NEEDS='zip perl ninja-build'",
    "apt-get install -y $DEB_NEEDS || dnf install -y $FED_NEEDS"
]
